#!/bin/sh
set -e
pip3 install 'sqlalchemy>=2.0.41'
pip3 install 'pdoc3>=0.11.6,<0.12.0'
pip3 install 'markdownify>=1.2.0,<2.0.0'
pip3 install 'pip-requirements-parser>=32.0.1,<33.0.0'
pip3 install 'pydoctor>=25.4.0,<26.0.0'
pip3 install 'fastmcp>=2.12.2,<3.0.0'
#DEBHELPER#
exit 0