name: Build macOS Wheel

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

permissions:
  contents: read

jobs:
  build-macos-wheel:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install Poetry
        run: pip install poetry

      - name: Build Wheel
        run: poetry build --format wheel

      - name: Upload Wheel Artifact
        uses: actions/upload-artifact@v4
        with:
          name: devildex-macos-wheel
          path: dist/*.whl
