# .github/workflows/build-wheel.yml
name: Build Python Wheel

on:
  push:
    branches:
      - master
  # Permette di avviare questo workflow manualmente dalla tab "Actions" di GitHub
  workflow_dispatch:

jobs:
  build:
    name: Build Wheel
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Poetry
        run: pip install poetry

      - name: Install system dependencies for wxPython
        # Queste sono necessarie per wxPython, che è una dipendenza di build
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.1-dev libxtst-dev

      - name: Configure Poetry and install dependencies
        run: |
          poetry config virtualenvs.in-project true
          # Installa solo le dipendenze, non il progetto stesso, che è corretto per una build
          poetry install --no-root

      - name: Build wheel
        run: poetry build --format wheel

      - name: Upload wheel artifact
        # Il file .whl sarà disponibile nella sezione "Artifacts" del workflow run
        uses: actions/upload-artifact@v4
        with:
          name: python-wheel
          path: dist/*.whl