name: Create Release on Keyword

on:
  push:
    branches:
      - main

jobs:
  create_release:
    if: contains(github.event.head_commit.message, 'release:')
    
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release v${{ github.run_number }}
          body: ${{ github.event.head_commit.message }}
          draft: false
          prerelease: false