name: Package Desktop Application

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

permissions:
  contents: write

jobs:
  build-package:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11" # Use a consistent Python version

      - name: Install Poetry
        run: pip install poetry

      - name: Install wxPython
        if: runner.os == 'Windows'
        run: pip install "wxpython==4.2.3"
      - name: Install wxPython
        if: runner.os == 'macOS'
        run: pip install "wxpython==4.2.3"
      - name: Install wxPython
        if: runner.os == 'Linux'
        run: pip install "https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-22.04/wxPython-4.2.2-cp311-cp311-linux_x86_64.whl"

      - name: Update poetry.lock
        run: poetry lock

      - name: Update poetry.lock
        run: poetry lock

      - name: Install Project Dependencies
        run: poetry install

      - name: Install OS-specific dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libnotify-dev \
            libgtk-3-dev \
            libsdl2-dev \
            libwebkit2gtk-4.1-dev \
            libxtst-dev \
            xvfb \
            bzr \
            python3-gi \
            python3-gi-cairo \
            python3-wxgtk4.0 \
            python3-wxgtk-webview4.0

      - name: Build Package
        run: poetry run pyinstaller pyinstaller_specs/devildex_${{ matrix.os }}.spec --distpath dist/${{ matrix.os }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: devildex-${{ matrix.os }}-build
          path: dist/${{ matrix.os }}/