name: Release Workflow

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - '**.txt'
      - '**.ini'
      - '**.toml'
      - '**.lock'
      - '**.sh'
      - '**.bat'
      - '**.bzl'
      - '**.png'
      - '**.xml'
      - '**.json'
      - '**.yaml'
      - '**.yml'
      - '**.gitignore'
      - '**.idea/**'
      - 'ci_dockerfiles/**'
      - 'ci_scripts/**'
      - 'imgs/**'
      - 'packaging/**'
      - 'pyinstaller_specs/**'
      - 'runner/**'
      - 'scripts/**'
      - 'source/**'
      - 'tests/**'
    tags-ignore:
      - '**'

jobs:
  release:
    runs-on: ubuntu-latest # Start with ubuntu-latest for initial setup
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Necessary to fetch all history for tags
        token: ${{ secrets.GITHUB_TOKEN }} # Automatically provided GitHub token

    - name: Configure Git
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "actions@github.com"

    - name: Debug pyproject.toml files
      run: |
        echo "Listing pyproject.toml files:"
        find . -name "pyproject.toml*"
        echo "Content of main pyproject.toml:"
        cat pyproject.toml

    - name: Get latest commit message
      id: commit_message
      run: |
        COMMIT_MSG=$(git log -1 --pretty=%B)
        echo "MESSAGE=$COMMIT_MSG" >> $GITHUB_OUTPUT

    - name: Determine version increment
      id: version_increment
      env:
        HEAD_COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
      run: |
        COMMIT_MESSAGE="${{ env.HEAD_COMMIT_MESSAGE }}"
        INCREMENT_TYPE=""
        if [[ "$COMMIT_MESSAGE" == "release(patch):"* ]]; then
          INCREMENT_TYPE="patch"
        elif [[ "$COMMIT_MESSAGE" == "release(minor):"* ]]; then
          INCREMENT_TYPE="minor"
        elif [[ "$COMMIT_MESSAGE" == "release(major):"* ]]; then
          INCREMENT_TYPE="major"
        fi
        echo "INCREMENT_TYPE=$INCREMENT_TYPE" >> "$GITHUB_OUTPUT"
        echo "Found increment type: $INCREMENT_TYPE"
    - name: Fail if no increment type found
      if: steps.version_increment.outputs.INCREMENT_TYPE == ''
      run: |
        echo "Commit message does not contain a valid release type (e.g., 'release(patch):', 'release(minor):', 'release(major):')."
        exit 0

    - name: Set up Python 3.13
      if: ${{ steps.version_increment.outputs.INCREMENT_TYPE != '' }}
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install jq
      if: ${{ steps.version_increment.outputs.INCREMENT_TYPE != '' }}
      run: sudo apt-get update && sudo apt-get install -y jq

    - name: Install Poetry
      if: ${{ steps.version_increment.outputs.INCREMENT_TYPE != '' }}
      run: pip install poetry

    - name: Get Build and Test Workflow Run ID
      id: get_build_and_test_run_id
      if: ${{ steps.version_increment.outputs.INCREMENT_TYPE != '' }}
      run: |
        REPO_OWNER="${{ github.repository_owner }}"
        REPO_NAME="${{ github.event.repository.name }}"
        COMMIT_SHA="${{ github.sha }}" # Use github.sha for push-triggered workflow
        WORKFLOW_NAME="Build and Test All Artifacts" # Name of the new workflow

        echo "Searching for '${WORKFLOW_NAME}' workflow run for commit SHA: ${COMMIT_SHA}"

        # Get workflow ID by name
        WORKFLOW_ID_RESPONSE=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                                    -H "Accept: application/vnd.github.v3+json" \
                                    "https://api.github.com/repos/${REPO_OWNER}/${REPO_NAME}/actions/workflows")
        WORKFLOW_ID=$(echo "${WORKFLOW_ID_RESPONSE}" | jq -r ".workflows[] | select(.name == \"${WORKFLOW_NAME}\") | .id")

        if [ "${WORKFLOW_ID}" == "null" ]; then
          echo "Error: Workflow '${WORKFLOW_NAME}' not found."
          exit 1
        fi

        RESPONSE=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                        -H "Accept: application/vnd.github.v3+json" \
                        "https://api.github.com/repos/${REPO_OWNER}/${REPO_NAME}/actions/runs?workflow_id=${WORKFLOW_ID}&head_sha=${COMMIT_SHA}&status=success&per_page=1")

        RUN_ID=$(echo "${RESPONSE}" | jq -r '.workflow_runs[0].id')

        if [ "${RUN_ID}" != "null" ]; then
          echo "Found '${WORKFLOW_NAME}' workflow run ID: ${RUN_ID}"
          echo "run_id=${RUN_ID}" >> "$GITHUB_OUTPUT"
        else
          echo "No successful '${WORKFLOW_NAME}' workflow run found for commit SHA: ${COMMIT_SHA}"
          echo "run_id=" >> "$GITHUB_OUTPUT"
          exit 1
        fi

    - name: Debug Poetry Version
      if: ${{ steps.version_increment.outputs.INCREMENT_TYPE != '' }}
      run: |
        echo "Current Poetry version: $(poetry version --short)"
        echo "Increment type: ${{ steps.version_increment.outputs.INCREMENT_TYPE }}"



    - name: Bump version with Poetry
      id: new_version
      if: ${{ steps.version_increment.outputs.INCREMENT_TYPE != '' }}
      run: |
        poetry version ${{ steps.version_increment.outputs.INCREMENT_TYPE }}
        NEW_VERSION=$(poetry version --short)
        echo "VERSION=$NEW_VERSION" >> $GITHUB_OUTPUT
        echo "New version set to: $NEW_VERSION"



    - name: Create artifacts directory
      if: ${{ steps.version_increment.outputs.INCREMENT_TYPE != '' }}
      run: mkdir -p artifacts/wheels artifacts/bundles artifacts/docs






    - name: Current Poetry Version
      if: ${{ steps.version_increment.outputs.INCREMENT_TYPE != '' }}
      run: poetry version --short



    - name: Commit version bump
      if: ${{ steps.version_increment.outputs.INCREMENT_TYPE != '' }}
      run: |
        git add pyproject.toml
        git commit -m "chore: Release v\"${{ steps.new_version.outputs.VERSION }}\"" || true

    - name: Add github remote
      if: ${{ steps.version_increment.outputs.INCREMENT_TYPE != '' }}
      run: |
        git remote add github https://github.com/${{ github.repository }}


    - name: Delete existing GitHub Release (if any)
      if: ${{ steps.version_increment.outputs.INCREMENT_TYPE != '' }}
      run: |
        export GH_TOKEN=${{ secrets.GITHUB_TOKEN }}
        gh release delete v${{ steps.new_version.outputs.VERSION }} --yes || true
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Ensure GH_TOKEN is available for gh CLI

    - name: Delete existing Git tag (if any)
      if: ${{ steps.version_increment.outputs.INCREMENT_TYPE != '' }}
      run: |
        git push --delete origin v${{ steps.new_version.outputs.VERSION }} || true
        git push --delete github v${{ steps.new_version.outputs.VERSION }} || true

    - name: Create Git tag
      if: ${{ steps.version_increment.outputs.INCREMENT_TYPE != '' }}
      run: git tag v${{ steps.new_version.outputs.VERSION }}

    - name: Push changes and tag
      if: ${{ steps.version_increment.outputs.INCREMENT_TYPE != '' }}
      run: |
        git push origin master -f
        git push origin v${{ steps.new_version.outputs.VERSION }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



    - name: Download Windows Wheel artifact
      if: ${{ steps.version_increment.outputs.INCREMENT_TYPE != '' }}
      uses: actions/download-artifact@v4
      with:
        run-id: ${{ steps.get_build_and_test_run_id.outputs.run_id }}
        repository: ${{ github.repository }}

    - name: Download macOS Wheel artifact
      if: ${{ steps.version_increment.outputs.INCREMENT_TYPE != '' }}
      uses: actions/download-artifact@v4
      with:
        name: devildex-macos-wheel
        path: artifacts/wheels/macos
        github-token: ${{ secrets.GITHUB_TOKEN }}
        run-id: ${{ steps.get_build_and_test_run_id.outputs.run_id }}
        repository: ${{ github.repository }}

    - name: Download Linux Wheel artifact
      if: ${{ steps.version_increment.outputs.INCREMENT_TYPE != '' }}
      uses: actions/download-artifact@v4
      with:
        run-id: ${{ steps.get_build_and_test_run_id.outputs.run_id }}
        repository: ${{ github.repository }}

    - name: Download Windows PyInstaller bundle
      if: ${{ steps.version_increment.outputs.INCREMENT_TYPE != '' }}
      uses: actions/download-artifact@v4
      with:
        name: devildex-windows-latest-build
        path: artifacts/bundles/windows
        github-token: ${{ secrets.GITHUB_TOKEN }}
        run-id: ${{ steps.get_build_and_test_run_id.outputs.run_id }}
        repository: ${{ github.repository }}

    - name: Download macOS PyInstaller bundle
      if: ${{ steps.version_increment.outputs.INCREMENT_TYPE != '' }}
      uses: actions/download-artifact@v4
      with:
        run-id: ${{ steps.get_build_and_test_run_id.outputs.run_id }}
        repository: ${{ github.repository }}

    - name: Download Linux PyInstaller bundle
      if: ${{ steps.version_increment.outputs.INCREMENT_TYPE != '' }}
      uses: actions/download-artifact@v4
      with:
        name: devildex-ubuntu-latest-build
        run-id: ${{ steps.get_build_and_test_run_id.outputs.run_id }}
        repository: ${{ github.repository }}

    - name: Download documentation artifact
      if: ${{ steps.version_increment.outputs.INCREMENT_TYPE != '' }}
      uses: actions/download-artifact@v4
      with:
        name: documentation-html
        path: artifacts/docs
        github-token: ${{ secrets.GITHUB_TOKEN }}
        run-id: ${{ steps.get_build_and_test_run_id.outputs.run_id }}
        repository: ${{ github.repository }}

    - name: Zip documentation
      if: ${{ steps.version_increment.outputs.INCREMENT_TYPE != '' }}
      run: |
        cd artifacts/docs
        zip -r devildex_documentation.zip ./*
        mv devildex_documentation.zip ../
        cd ../..

    - name: List Artifacts Directory (after download)
      if: ${{ steps.version_increment.outputs.INCREMENT_TYPE != '' }}
      run: ls -R artifacts/

    - name: Create GitHub Release
      if: ${{ steps.version_increment.outputs.INCREMENT_TYPE != '' }}
      env:
        COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Ensure GH_TOKEN is available for gh CLI
      uses: softprops/action-gh-release@v2
      with:
        body: |
          Automated release for version v${{ steps.new_version.outputs.VERSION }}
          
          ${{ env.COMMIT_MESSAGE }}
        tag_name: v${{ steps.new_version.outputs.VERSION }}
        name: Release v${{ steps.new_version.outputs.VERSION }}
        draft: false
        prerelease: false
        files: |
          artifacts/wheels/windows/*.whl
          artifacts/wheels/macos/*.whl
          artifacts/wheels/linux/*.whl
          artifacts/bundles/windows/devildex_windows/*
          artifacts/bundles/macos/devildex_macos/*
          artifacts/bundles/linux/devildex_linux/*
          artifacts/devildex_documentation.zip