name: Release Please

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write
  issues: write # Added issues:write permission

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          release-type: python
          token: ${{ secrets.PAT_TOKEN }} # Use the correct PAT secret name
          skip-github-pull-request: true # Skip creating pull requests
          version-file: pyproject.toml # Specify pyproject.toml as the version file