name: Release Please

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          release-type: python
          package-name: devildex
          # The GITHUB_TOKEN is automatically provided by GitHub Actions.
          # It has sufficient permissions if the workflow has 'contents: write' and 'pull-requests: write'.
          token: ${{ secrets.GITHUB_TOKEN }}
