name: Test Packaged Application

on:
  workflow_run:
    workflows: ["Package Desktop Application"]
    types:
      - completed

jobs:
  test-package:
    runs-on: ${{ matrix.os }}

    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
      - name: Download all workflow artifacts
        uses: actions/download-artifact@v4
        with:
          name: devildex-${{ matrix.os }}-build
          path: build/
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}

      - name: List downloaded files
        run: ls -R build/

      - name: Test Built Application
        run: |
          if ("${{ runner.os }}" -eq "Windows") {
            Start-Process -FilePath ".\build\devildex_windows.exe" -NoNewWindow -PassThru | Wait-Process -Timeout 5
            Stop-Process -Name "devildex_windows.exe" -ErrorAction SilentlyContinue
          } elseif ("${{ runner.os }}" -eq "macOS") {
            chmod +x ./build/devildex_macos
            ./build/devildex_macos &
            sleep 5
            kill %1
          } elseif ("${{ runner.os }}" -eq "Linux") {
            chmod +x ./build/devildex_linux
            ./build/devildex_linux &
            sleep 5
            kill %1
          }
