name: Test Packaged Application

on:
  workflow_run:
    workflows: ["Build and Test All Artifacts"]
    types:
      - completed

jobs:
  test-windows-package:
    runs-on: windows-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: devildex-windows-bundle
          path: build/
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}

      - name: List downloaded files (Windows)
        run: ls -R build/

      - name: Test Built Application (Windows)
        run: |
          $process = Start-Process -FilePath ".\build\devildex_windows.exe" -NoNewWindow -PassThru
          Start-Sleep -Seconds 30
          if ($process.HasExited) {
              Write-Error "Application exited prematurely."
              exit 1
          } else {
              Stop-Process -Id $process.Id -ErrorAction SilentlyContinue
              Write-Host "Application remained running for 30 seconds."
          }

  test-macos-package:
    runs-on: macos-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Download macOS artifact
        uses: actions/download-artifact@v4
        with:
          name: devildex-macos-bundle
          path: build/
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}

      - name: List downloaded files (macOS)
        run: ls -R build/

      - name: Test Built Application (macOS)
        run: |
          chmod +x ./build/devildex_macos
          ./build/devildex_macos &
          PID=$!
          sleep 30
          if ps -p $PID > /dev/null; then
              kill $PID
              echo "Application remained running for 30 seconds."
          else
              echo "Application exited prematurely."
              exit 1
          fi

  test-linux-package:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Download Linux artifact
        uses: actions/download-artifact@v4
        with:
          name: devildex-debian-package
          path: build/deb/
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}

      - name: List downloaded files (Linux)
        run: ls -R build/

      - name: Test Built Application (Linux)
        run: |
          sudo apt-get update
          sudo apt-get install -y ./build/deb/*.deb
          export PATH="/usr/bin:$PATH"
          devildex &
          PID=$!
          sleep 30
          if ps -p $PID > /dev/null; then
              kill $PID
              echo "Application remained running for 30 seconds."
          else
              echo "Application exited prematurely."
              exit 1
          fi

  test-linux-wheel-package:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Download Linux Wheel artifact
        uses: actions/download-artifact@v4
        with:
          name: devildex-linux-wheel-artifact
          path: build/wheel/
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}

      - name: List downloaded files (Linux Wheel)
        run: ls -R build/wheel/

      - name: Test Installed Wheel (Linux)
        run: |
          pip install ./build/wheel/*.whl
          python -c "import devildex; import subprocess; p = subprocess.Popen(['devildex']); import time; time.sleep(30); p.poll() or p.terminate(); exit(0) if p.returncode is None else exit(1)"

  test-pyinstaller-windows-package:
    runs-on: windows-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Download PyInstaller Windows bundle
        uses: actions/download-artifact@v4
        with:
          name: devildex-windows-bundle
          path: build/windows-latest/
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
      - name: List downloaded files (PyInstaller Windows)
        run: ls -R build/windows-latest/

      - name: Test Built Application (PyInstaller Windows)
        run: |
          $process = Start-Process -FilePath ".\build\windows-latest\devildex_windows.exe" -NoNewWindow -PassThru
          Start-Sleep -Seconds 30
          if ($process.HasExited) {
              Write-Error "Application exited prematurely."
              exit 1
          } else {
              Stop-Process -Id $process.Id -ErrorAction SilentlyContinue
              Write-Host "Application remained running for 30 seconds."
          }

  test-pyinstaller-macos-package:
    runs-on: macos-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Download PyInstaller macOS bundle
        uses: actions/download-artifact@v4
        with:
          name: devildex-macos-bundle
          path: build/macos-latest/
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
      - name: List downloaded files (PyInstaller macOS)
        run: ls -R build/macos-latest/

      - name: Test Built Application (PyInstaller macOS)
        run: |
          chmod +x ./build/macos-latest/devildex_macos
          ./build/macos-latest/devildex_macos &
          PID=$!
          sleep 30
          if ps -p $PID > /dev/null; then
              kill $PID
              echo "Application remained running for 30 seconds."
          else
              echo "Application exited prematurely."
              exit 1
          fi

  test-pyinstaller-linux-package:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Download PyInstaller Linux bundle
        uses: actions/download-artifact@v4
        with:
          name: devildex-linux-bundle
          path: build/ubuntu-latest/
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
      - name: List downloaded files (PyInstaller Linux)
        run: ls -R build/ubuntu-latest/

      - name: Test Built Application (PyInstaller Linux)
        run: |
          chmod +x ./build/ubuntu-latest/devildex_linux
          ./build/ubuntu-latest/devildex_linux &
          PID=$!
          sleep 30
          if ps -p $PID > /dev/null; then
              kill $PID
              echo "Application remained running for 30 seconds."
          else
              echo "Application exited prematurely."
              exit 1
          fi

  test-rpm-package:
    runs-on: fedora-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Download RPM package
        uses: actions/download-artifact@v4
        with:
          name: devildex-rpm-package
          path: build/rpm/
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
      - name: List downloaded files (RPM)
        run: ls -R build/rpm/

      - name: Test Built Application (RPM)
        run: |
          sudo dnf install -y ./build/rpm/*.rpm
          devildex &
          PID=$!
          sleep 30
          if ps -p $PID > /dev/null; then
              kill $PID
              echo "Application remained running for 30 seconds."
          else
              echo "Application exited prematurely."
              exit 1
          fi
