name: Test Packaged Application

on:
  workflow_run:
    workflows: ["Package Desktop Application"]
    types:
      - completed

jobs:
  test-package:
    runs-on: ${{ matrix.os }}

    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
      - name: Download all workflow artifacts
        uses: actions/download-artifact@v4
        with:
          name: devildex-${{ matrix.os }}-build
          path: build/
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}

      - name: List downloaded files
        run: ls -R build/

      - name: Test Built Application
        run: |
          if [ "${{ runner.os }}" == "Windows" ]; then
            ./build/devildex_windows.exe &
            sleep 5
            kill %1
          elif [ "${{ runner.os }}" == "macOS" ]; then
            chmod +x ./build/devildex_macos
            ./build/devildex_macos &
            sleep 5
            kill %1
          elif [ "${{ runner.os }}" == "Linux" ]; then
            chmod +x ./build/devildex_linux
            ./build/devildex_linux &
            sleep 5
            kill %1
          fi
