"""Add ProjectDocRequirements model

Revision ID: 6f3d4a909e9e
Revises: 78c459e1a2ab
Create Date: 2025-10-20 19:14:09.825272

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6f3d4a909e9e'
down_revision: Union[str, Sequence[str], None] = '78c459e1a2ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_doc_requirements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('package_name', sa.String(), nullable=False),
    sa.Column('builder_type', sa.String(), nullable=False),
    sa.Column('requirements_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['package_name'], ['package_info.package_name'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('package_name', 'builder_type', name='uq_project_doc_requirements')
    )
    op.create_index(op.f('ix_project_doc_requirements_builder_type'), 'project_doc_requirements', ['builder_type'], unique=False)
    op.create_index(op.f('ix_project_doc_requirements_id'), 'project_doc_requirements', ['id'], unique=False)
    op.create_index(op.f('ix_project_doc_requirements_package_name'), 'project_doc_requirements', ['package_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_doc_requirements_package_name'), table_name='project_doc_requirements')
    op.drop_index(op.f('ix_project_doc_requirements_id'), table_name='project_doc_requirements')
    op.drop_index(op.f('ix_project_doc_requirements_builder_type'), table_name='project_doc_requirements')
    op.drop_table('project_doc_requirements')
    # ### end Alembic commands ###
