"""Add notes column to docset

Revision ID: 78c459e1a2ab
Revises: ffaf7e5c74e4
Create Date: 2025-10-04 10:49:58.220283

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '78c459e1a2ab'
down_revision: Union[str, Sequence[str], None] = 'ffaf7e5c74e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('docset', sa.Column('notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('docset', 'notes')
    # ### end Alembic commands ###
