from collections.abc import Sequence
from typing import Union

from alembic import op

from devildex.database.models import Base

"""Create initial schema manually.

Revision ID: ffaf7e5c74e4
Revises:
Create Date: 2025-10-04 10:42:56.917457

"""


# revision identifiers, used by Alembic.
revision: str = 'ffaf7e5c74e4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    Base.metadata.create_all(bind=op.get_bind())
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('docset')
    op.drop_table('project')
    # ### end Alembic commands ###
